Add build for node exporter
project-flotta/rfe-ansible-playbooks pull request #7
Opened 2022-02-10 13:12 UTC by jordigilh

* Adds rpm build for `node_exporter`
* Changed description for some ansible tasks to match best its actual outcome 

@eloycoto @pkliczewski @jakub-dzon @masayag can you take a look at your discretion?

2022-02-11 15:43 UTC, pkliczewski approved these changes

2022-02-11 16:13 UTC, jakub-dzon requested changes

2022-02-11 16:13 UTC, jakub-dzon commented on ansible/roles/build-node-exporter/tasks/main.yaml
> +    patterns: '^flotta-agent-.*\.rpm$'
I think in this case that should be '^node_exporter-.*\.rpm$'

2022-02-11 16:13 UTC, jakub-dzon commented on ansible/roles/build-node-exporter/tasks/main.yaml
> +  register: agent_rpm
`node_exporter_rpm`?

2022-02-11 17:14 UTC, jordigilh commented on ansible/roles/build-node-exporter/tasks/main.yaml
> +  register: agent_rpm
agreed.

2022-02-11 17:46 UTC, eloycoto approved these changes

2022-02-11 21:04 UTC, masayag approved these changes

2022-02-14 07:17 UTC, jakub-dzon approved these changes

2022-02-14 07:17 UTC, merged